# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    #alias grep='grep --color=auto'
    #alias fgrep='fgrep --color=auto'
    #alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
#alias bmatlab='matlab -nodisplay'
#alias syncccub2loc='rsync -rtvue ssh je0377ro@ssh-ccub.u-bourgogne.fr:/work/imb/je0377ro/Sync/Works/ /data/ccub/Works/ --delete'
#alias syncloc2ccub='rsync -rtvue ssh /data/ccub/Works/ je0377ro@ssh-ccub.u-bourgogne.fr:/work/imb/je0377ro/Sync/Works/ --delete'
#
#alias syncccub2loc2='rsync -rtvue ssh --delete je0377ro@ssh-ccub.u-bourgogne.fr:/work/imb/je0377ro/Sync/WorksPD/ /data/ccub/WorksPD/ --delete'
#alias syncloc2ccub2='rsync -rtvue ssh /data/ccub/WorksPD/ je0377ro@ssh-ccub.u-bourgogne.fr:/work/imb/je0377ro/Sync/WorksPD/ --delete'
#
#alias syncccub2loc3='rsync -rtvue ssh --delete je0377ro@ssh-ccub.u-bourgogne.fr:/work/imb/je0377ro/Sync/WorksEPF/ /data/ccub/WorksEPF/ --delete'
#alias syncloc2ccub3='rsync -rtvue ssh /data/ccub/WorksEPF/ je0377ro@ssh-ccub.u-bourgogne.fr:/work/imb/je0377ro/Sync/WorksEPF/ --delete'

#alias syncccub2loc='rsync -rtvue ssh --delete je0377ro@ssh-ccub.u-bourgogne.fr:/work/imb/je0377ro/Sync/ /home/fernand/data/ccub/ --delete'
#alias syncloc2ccub='rsync -rtvue ssh /home/fernand/data/ccub/ je0377ro@ssh-ccub.u-bourgogne.fr:/work/imb/je0377ro/Sync/ --delete'

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

#alias pdfocr='~/bin/pdfocr-master/pdfocr.rb'

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi


#alias unimath='unison mathrice && unison plmbox'
#alias unimath='unison plmbox'
#alias allSync='syncccub2loc && unison ccub && unison ccubPD && unison ccubEPF && syncloc2ccub'
#alias allSync='unison ccub && unison ccubPD && unison ccubEPF '
alias bmathematica='/opt/Mathematica11/Executables/math'
alias mathematica='/opt/Mathematica11/Executables/mathematica'
alias matlab='/opt/MATLAB/R2017a/bin/matlab'
alias bmatlab='/opt/MATLAB/R2017a/bin/matlab -nodisplay -nodesktop'
alias maple='/opt/maple2017/bin/xmaple -jvm'
alias bmaple='/opt/maple2017/bin/maple'
alias bscilab='scilab-adv-cli'
alias boctave='flatpak run org.octave.Octave --gui'
alias shutlight='xset -display :0.0 dpms force off'
alias bmaxima='cd ~/bin/moodle-qtype_stack-master/stack/maxima && maxima --init-mac=~/bin/moodle-qtype_stack-master/stack/maxima/sandbox.wxm'
alias blatex='/data/Resilio/Work/Tuyaus/Scripts/bin/init_latex/init_latex.sh'
alias bsage='/data/sage/SageMath/sage'

export TAPENADE_HOME=~/bin/tapenade3.13
export PATH=$PATH:~/bin/Bocop-2.1.0-linux-src/qtgui
export PATH=$PATH:~/bin/hampath304/bin
export PATH=$PATH:/data/Resilio/Work/Tuyaus/Scripts/system
export PATH=$PATH:~/bin/hampathSampled/bin
export PATH=$PATH:~/bin/hampath211/bin
export PATH=$PATH:~/bin/tapenade3.13/bin
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre
export PATH=$PATH:/usr/lib/jvm/java-8-openjdk-amd64/jre/bin
export PATH=$PATH:~/bin/mosek/8/tools/platform/linux64x86/bin
export PATH=$PATH:~/mainLoc/Tuyaus/Scripts/system

export EDITOR=vim
export MOSEKLM_LICENSE_FILE=~/bin/mosek/mosek.lic

if [ -n "$DISPLAY" ]; then
    xset b off
fi

#remove the bell sound
#sudo modprobe -r pcspkr
alias myshutdown='sudo modprobe -r pcspkr && sudo shutdown'

#system bell
if [ -n "$DISPLAY" ]; then
  xset b off
fi

#rm -rf ~/mainLoc/Tuyaus/Scripts/ptvim
#cp -r ~/.vim /home/fernand/mainLoc/Tuyaus/Scripts/ptvim


# added by Anaconda3 installer
#export PATH="/home/fernand/bin/anaconda3/bin:$PATH"


alias evinc='flatpak run org.gnome.Evince'
alias muze='flatpak run org.gnome.Rhythmbox3'
alias geog='flatpak run org.geogebra.GeoGebra'

screenfetch
