
# This file was *autogenerated* from the file exo1.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_0p0423466213 = RealNumber('0.0423466213'); _sage_const_0p25 = RealNumber('0.25'); _sage_const_20 = Integer(20); _sage_const_2p = RealNumber('2.')
from sage import *

reset()

import numpy as np
import pylab as plt

a=-_sage_const_0p25 ;
b=_sage_const_1 ;
N=_sage_const_20 ;
h=(b-a)/(N-_sage_const_1 );

tn=a;
yn=-_sage_const_0p0423466213 ;

def odef(t,y):
  return (nroot(y,_sage_const_5 ))**_sage_const_2 

def nroot(x,q):
  if mod(q,_sage_const_2 )==_sage_const_1 :
    return x.sign()*(abs(x)**(_sage_const_1 /q));
  else:
    return x**(_sage_const_1 /q);
    

k=-_sage_const_1 ;
for i in range(_sage_const_1 ,N):
  k1=h*odef(tn,yn)
  k2=h*odef(tn+h,yn+k1)
  yold=yn;
  yn = yn + (k1+k2)/_sage_const_2p 
  if yold*yn<_sage_const_0 :
    k=i;
    print(k)
  tn = tn+h

print(yn,k)


