
# This file was *autogenerated* from the file exo3.sage
from sage.all_cmdline import *   # import sage library

_sage_const_30 = Integer(30); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_16 = Integer(16); _sage_const_2 = Integer(2)
from sage import *

reset()

import numpy as np
import pylab as plt


alp=np.array([-_sage_const_1 ,_sage_const_16 ,-_sage_const_30 ,_sage_const_16 ,-_sage_const_1 ])
bet=np.array([_sage_const_2 ,_sage_const_1 ,_sage_const_0 ,-_sage_const_1 ,-_sage_const_2 ])
bet2 =bet*bet
bet3 =bet*bet2

print(sum(alp*bet))
print(sum(alp*bet2))
print(sum(alp*bet2))


