
# This file was *autogenerated* from the file exo4.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_9p = RealNumber('9.'); _sage_const_1p = RealNumber('1.'); _sage_const_3p = RealNumber('3.'); _sage_const_300 = Integer(300); _sage_const_2p = RealNumber('2.'); _sage_const_5p = RealNumber('5.')
from sage import *

reset()

import numpy as np
import pylab as plt

f=open("toto.txt", "r")
f1=f.readlines()
ut=[float(item) for item in f1[_sage_const_0 ].split() if item]

a=_sage_const_2 ;
c=_sage_const_4 ;
d=_sage_const_3 ;

def odef(n,q):
  return np.array([_sage_const_1p -_sage_const_3 /c*q[_sage_const_1 ]*q[_sage_const_2 ]+_sage_const_1 /a*q[_sage_const_0 ]+_sage_const_1 /c*q[_sage_const_2 ]**_sage_const_3 ,q[_sage_const_2 ]/d,ut[n]])

qn = np.array([-_sage_const_1 /_sage_const_5p ,_sage_const_1 /_sage_const_9p ,-_sage_const_1 /_sage_const_3p ])
N=_sage_const_300 
h=_sage_const_2p *n(pi)/N 
for n in range(_sage_const_0 ,N):
  print(ut[n])
  k1 = h * odef(n,qn)
  k2 = h * odef(n+_sage_const_1 ,qn+k1)
  qn = qn + (k1+k2)/_sage_const_2p 


print(qn)


